### ISSUE TITLE
Only one core support ?

### ISSUE THREAD

**Issue by damoebius** [orangepi-xunlong/OrangePiH6_Linux4_9#2]
Hi,
I installed the latest image OrangePi_3_Linux_4.9_Ubuntu16.04_Server_emmc_v1.0.tar.gz but i have only one core working, others are offline.

    root@OrangePi:~# lscpu
    Architecture: aarch64
    Byte Order: Little Endian
    CPU(s): 4
    On-line CPU(s) list: 0
    Off-line CPU(s) list: 1-3
    Thread(s) per core: 1
    Core(s) per socket: 1
    Socket(s): 1
    CPU max MHz: 1488.0000
    CPU min MHz: 480.0000
    Hypervisor vendor: horizontal
    Virtualization type: full

I tried to enable them with  echo 1 > /sys/devices/system/cpu/cpu1/online but they still are off line.

    Mar 23 22:02:37 orangepi kernel: [16811.140461] CPU1: Booted secondary processor [410fd034]
    Mar 23 22:02:37 orangepi kernel: [16811.151327] Invalid sched_group_energy for CPU1
    Mar 23 22:02:37 orangepi kernel: [16811.151346] Invalid sched_group_energy for Cluster1
    Mar 23 22:02:37 orangepi kernel: [16811.151358] Invalid sched_group_energy for CPU0
    Mar 23 22:02:37 orangepi kernel: [16811.151372] Invalid sched_group_energy for Cluster0
    Mar 23 22:02:37 orangepi kernel: [16811.157811] CPU0: update max cpu_capacity 1024
    Mar 23 22:02:37 orangepi kernel: [16811.371322] Invalid sched_group_energy for CPU0
    Mar 23 22:02:37 orangepi kernel: [16811.371340] Invalid sched_group_energy for Cluster0
    Mar 23 22:02:37 orangepi kernel: [16811.388675] CPU1: shutdown
    Mar 23 22:02:37 orangepi kernel: [16811.388695] psci: CPU1 killed.

What's wrong ?

**Comment by SergeyStaroletov** [comment]
may be it is because of a funny software for energy saving, it is stopping cpus by killing them. Just load your system and you will see 2-3-4 cpus:)

**Comment by tuxd3v** [comment]
Hi,
When you compile the Kernel,
On DTS compilation does you get:
"Script_to_dts: Can not find [sun50iw6p1-petrel-p1.dts]. Will use common dts file instead." ?

Does anny one knows what is the petrel?

Thanks in Advance,
Regards

**Comment by SergeyStaroletov** [comment]
> Hi,
> When you compile the Kernel,
> On DTS compilation does you get:
> "Script_to_dts: Can not find [sun50iw6p1-petrel-p1.dts]. Will use common dts file instead." ?
> 
> Does anny one knows what is the petrel?
> 
> Thanks in Advance,
> Regards

For me it compiled without any errors by flashing ubuntu with 4.9 kernel from orangepi site, boot it with opi3 then get the tools and some packets, go to kernel source tree, then do building 
make oldconfig
make prepare 
make menuconfig
make -j 4

may be you use  wrong config settings. 
I was able to build my .dtb and use it in boot loader with my custom kernel.

**Comment by cseattila** [comment]
Yes, SergeyStaroletov was right.
<pre>
 root@OrangePi:/lib/modules/4.9.118+/kernel/drivers/net# lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0
Off-line CPU(s) list:  1-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
CPU max MHz:           1488.0000
CPU min MHz:           480.0000
Hypervisor vendor:     horizontal
Virtualization type:   full
root@OrangePi:/lib/modules/4.9.118+/kernel/drivers/net# yes >/dev/null
^C
root@OrangePi:/lib/modules/4.9.118+/kernel/drivers/net# yes >/dev/null &
[1] 5794
root@OrangePi:/lib/modules/4.9.118+/kernel/drivers/net# lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0,1
Off-line CPU(s) list:  2,3
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
CPU max MHz:           1488.0000
CPU min MHz:           480.0000
Hypervisor vendor:     horizontal
Virtualization type:   full
root@OrangePi:/lib/modules/4.9.118+/kernel/drivers/net#
</pre>
